### ISSUE TITLE
Some questions about this library

### ISSUE THREAD

**Issue by pioneerAlone** [PonomarevDA/libparams#25]
**Question #1:**
int8_t res;
    if (0 == romWrite(0, (uint8_t*)integer_values_pool, INT_VAL_POOL_SIZE)) {
        res = LIBPARAMS_UNKNOWN_ERROR;
    }
   **//Why do you use "else if" instead of "if" here? It should always try to save both.**
    **else if (**0 == romWrite(paramsGetStringMemoryPoolAddress(),
                             (uint8_t*)string_values_pool,
                             STR_VAL_POOL_SIZE)) {
        res = LIBPARAMS_UNKNOWN_ERROR;
    } else {
        res = LIBPARAMS_OK;
    }
    
**Questions #2:**
**I understand that interger_values_pool and string_values_pool are stored sequentially, so storing string_values_pool should be offset+ INT_VAL_POOL_SIZE, so paramsGetStringMemoryPoolAddress(), I don't understand the intention of this function**.

void paramsLoadFromFlash() {
    romRead(0, (uint8_t*)integer_values_pool, INT_VAL_POOL_SIZE);
    romRead(**paramsGetStringMemoryPoolAddress**(), (uint8_t*)&string_values_pool, STR_VAL_POOL_SIZE);

    for (uint_fast8_t idx = 0; idx < integer_params_amount; idx++) {
        IntegerParamValue_t val = integer_values_pool[idx];
        if (val < integer_desc_pool[idx].min || val > integer_desc_pool[idx].max) {
            integer_values_pool[idx] = integer_desc_pool[idx].def;
        }
    }
}

static uint32_t **paramsGetStringMemoryPoolAddress**() {
    return romGetAvailableMemory() - MAX_STRING_LENGTH * string_params_amount; 
}

**Comment by PonomarevDA** [comment]
> Why do you use "else if" instead of "if" here? It should always try to save both

From romWrite it is always expected to be successfully executed withing the storage.c scope. An error means either a library internal error or the provided flash driver is incorrect. If you detect such an error I think the safest idea is just to stop writing immediately to avoid doing something wrong.
What I didn't consider here is that we can have zero integers, so romWrite will always return 0. I will fix that.
I can also try to use more meaningful names for errors like LIBPARAMS_INTERNAL_ERROR.

> I understand that interger_values_pool and string_values_pool are stored sequentially

It sounds like a lack of the documentation. I will deal with it.
Your statement is incorrect. If you allocate a storage in a single page, all integers are stored in the beginning of the page and all strings are stored in the end of the page. For example, stm32f103 with page size 1 KByte can have the following allocation:

| Param          | Offset from the page start, bytes | Size, Bytes  |
| -------------- | ---------------------------------- | ----------- |
| First integer  | 0                                  | 4           |
| Second integer | 4                                  | 4           |
| Third integer  | 8                                  | 4           |
| ...            | ...                                | ...         |
| First string   | 1024 - 56 * 3                      | 56          |
| Second string  | 1024 - 56 * 2                      | 56          |
| Third string   | 1024 - 56 * 1                      | 56          |

The intention of this type of allocation is simple. At the moment the library can't detect when a user uploads firmware with a new set of parameters. Adding new parameter, deleting an existing one or swapping them caused the library to interpret them incorrectly. Since stings and integers are separated, a new integer will only corrupt the storage of integers but not strings. It is not the finite solution of the problem, but it makes the development easier.

**Comment by pioneerAlone** [comment]
Got it, thanks for your clarification.
