### ISSUE TITLE
How to write your own yaml file

### ISSUE THREAD

**Issue by pioneerAlone** [PonomarevDA/libparams#27]
Hello,

I started writing own yaml file, but I have doubts about some options.

#1 A device node id
#2 Set a system name
#3 Define a publisher is used to report data collected by sensors, using uavcan natural8 type

Questions:
1） Once I want to use a standard data type, I should specify type as "port", right?
2)    The Port type will create two data structures, integer and string at the same time. Can I specify default, min, and max for the port type (I set it, but it will not generate these contents)

`uavcan.node.id:
  type: Integer
  enum: PARAM_NODE_ID
  flags: immutable
  default: 50
  min: 0
  max: 127

system.name:
  type: String
  enum: PARAM_SYSTEM_NAME
  flags: immutable
  default: "STM32x"

uavcan.pub.det:
  type: Port
  data_type: uavcan.primitive.scalar.natural8
  enum_base: PARAM_DET_SCALAR
  flags: mutable
  default: 0
  min: 0
  max: 255`

**Comment by PonomarevDA** [comment]
Hello,

> Once I want to use a standard data type, I should specify type as "port", right?

It is expected to use port instead of creating integer and string separately just because it is a short form, so it reduces the chance of making a typo.
You can use it for both public regulated data types and custom data types.

> The Port type will create two data structures, integer and string at the same time. Can I specify default, min, and max for the port type (I set it, but it will not generate these contents)

According to the specification, Port ID has type natural16 and it can be [0; 8191] when enabled and 65535 when unset. The recommended default value is 65535. That's why I didn't consider a way to set custom min, max and def values.
While I can find it interesting to add an optional custom default value (this is not recommended, but not prohibited by the standard) , I'm not sure why do we need to change min and max.
If you need customization, you can always create these parameters separately.

I will update the README.md and create more examples later to make the purpose clear.

**Comment by pioneerAlone** [comment]
Thanks, got it.
